components:
  examples:
    feedAccessResponse:
      value:
        activities-heart:
        - customHeartRateZones: []
          dateTime: today
          heartRateZones:
          - caloriesOut: 138.8351
            max: 86
            min: 30
            minutes: 65
            name: Out of Range
          - caloriesOut: 309.96824
            max: 120
            min: 86
            minutes: 177
            name: Fat Burn
          - caloriesOut: 198.6678
            max: 146
            min: 120
            minutes: 59
            name: Cardio
          - caloriesOut: 8.1326
            max: 220
            min: 146
            minutes: 7
            name: Peak
          value: '102.28'
        activities-heart-intraday:
          dataset:
          - time: '12:00:00'
            value: 111
          - time: '12:01:00'
            value: 97
          - time: '12:02:00'
            value: 112
          - time: '12:03:00'
            value: 114
          - time: '12:04:00'
            value: 136
          datasetInterval: 1
          datasetType: minute
    feedList:
      value:
        CE22UFPUKSW77IA26A2OKHVKEA3RU6ES:
          connection: https://dev2-user.testonly.digital-me.nl/user/connections/user/fp_rp_dev2/43c5c576-c0d0-4fdd-8593-a57dacdb1a2f
          created: 1565083781575
          lastUpdated: 1565083781626
          protocol: https://github.com/qiyfoundation/fiKks/tree/master/schema/v1
          status: Message sent
        PYSSVYZLIDBI5YDGHA6ONFWMTON4T2U3:
          connection: https://dev2-user.testonly.digital-me.nl/user/connections/user/fp_rp_dev2/f3f5c1d1-61c0-45fd-9faa-f7d377dd89e3
          created: 1564985247891
          lastUpdated: 1564985247945
          protocol: https://github.com/qiyfoundation/fiKks/tree/master/schema/v1
          status: Sending message failed
        QZJ5MOWNEXARVTTBWMYZAO7ISYOQQOAU:
          connection: https://dev2-user.testonly.digital-me.nl/user/connections/user/fp_rp_dev2/43c5c576-c0d0-4fdd-8593-a57dacdb1a2f
          created: 1565083591605
          lastUpdated: 1565083591687
          protocol: https://github.com/qiyfoundation/fiKks/tree/master/schema/v1
          status: Created
        RIUDDVYZLIDBI5YDGHAONFWMTON4INH78:
          connection: https://dev2-user.testonly.digital-me.nl/user/connections/user/fp_rp_dev2/f3f5c1d1-61c0-45fd-9faa-f7d377dd89e3
          created: 1564985247891
          lastUpdated: 1564985247945
          protocol: https://github.com/qiyfoundation/fiKks/tree/master/schema/v1
          status: Ready to resolve
    feedRequest:
      value:
        input: Im9wdGlvbmFsIG9wZXJhdGlvbiBib2R5IGVuY29kZWQgYXMgYSBiYXNlNjQgZW5jb2RlZCBieXRlIGFycmF5Ig==
        protocol: https://github.com/qiyfoundation/payment-due-list/tree/master/schema/v1
        text: Requesting feed.
    feedRequestCallback:
      value:
        connectionUrl: https://dev2-user.testonly.digital-me.nl/user/connections/user/pt_usernode_fksH_de/d3b58af4-2883-4cef-b203-41e117549906
        extraData: BZWEKR63P2FEJZXYLGBN3XNWCBZU6FZG
        type: DATA_REFERENCE_RECEIVED2
    feedRequestResponse:
      value:
        feedId: 3J2UVSFIAH6X77HXR4MVHBVNG46GWT3M
        protocol: https://github.com/qiyfoundation/payment-due-list/tree/master/schema/v1
    feedsAccessRequest:
      value:
        '{{feed_id1}}':
          input: <optional json member with base-64 encrypted byte array>
        '{{feed_id2}}':
          input: <optional json member with base-64 encrypted byte array>
    feedsAccessResponse:
      value:
        <feed_id1>:
          content-type: application/xml
          error: null
          output: <base64-encoded feed_id1 access response>
        <feed_id2>:
          content-type: application/json
          error: null
          output: <base64-encoded feed_id2 access response>
  parameters:
    feedId:
      in: path
      name: feedId
      required: true
      schema:
        $ref: '#/components/schemas/feedId'
    feedsEndpointPath:
      description: Feeds Endpoint path, for example 'user/mgd_dev2/feeds' for the
        Connection Feeds Endpoint 'https://dev2-user.testonly.digital-me.nl/user/mgd_dev2/feeds'.
      in: path
      name: FeedsEndpointPath
      required: true
    protocol:
      explode: true
      in: query
      name: protocol
      required: false
      schema:
        $ref: '#/components/schemas/protocol'
      style: form
  responses:
    default:
      $ref: https://raw.githubusercontent.com/qiyfoundation/Qiy-Scheme/review-board/Qiy-Node/openapi.json#/components/responses/default
    feedAccessResponse:
      content:
        application/json:
          examples:
            Feed response:
              $ref: '#/components/examples/feedAccessResponse'
          schema:
            $ref: '#/components/schemas/feedAccessResponse'
      description: Feed access response
    feedList:
      content:
        application/json:
          examples:
            example:
              $ref: '#/components/examples/feedList'
          schema:
            $ref: '#/components/schemas/feedList'
      description: Feed list
    feedRequestCallback:
      description: Request for Feed Callback response
    feedRequestResponse:
      content:
        application/json:
          examples:
            feed:
              $ref: '#/components/examples/feedRequestResponse'
          schema:
            $ref: '#/components/schemas/feedRequestResponse'
      description: Feed request response
    feedsAccessResponse:
      content:
        application/json:
          examples:
            Feeds response:
              $ref: '#/components/examples/feedsAccessResponse'
          schema:
            $ref: '#/components/schemas/feedsAccessResponse'
      description: Feeds access response
  schemas:
    dataReferenceReceivedv2Event:
      description: See [Data Reference Received-v2 Event](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#data-reference-received-v2-event)
      properties:
        connectionUrl:
          format: url
          maxItems: 1
          minItems: 1
          type: string
        extraData:
          anyOf:
          - properties:
              protocol:
                description: Service type url
                format: url
                maxItems: 1
                minItems: 1
                type: string
              value:
                description: Feed id
                maxItems: 1
                minItems: 1
                type: string
            type: object
          - description: feed id
            type: string
        type:
          description: Event type
          enum:
          - DATA_REFERENCE_RECEIVED2
          maxItems: 1
          minItems: 1
          type: string
      type: object
    feedAccessResponse:
      description: The feed response format is described in the service type description
    feedDetails:
      properties:
        connection:
          description: Connection url
          format: url
          maxItems: '1'
          minItems: '1'
          type: string
        created:
          description: Creation datetimestamp
          format: Unix time in mili seconds
          maxItems: '1'
          minItems: '1'
          type: number
        lastUpdated:
          description: Last updated datetimestamp
          format: Unix time in mili seconds
          maxItems: '1'
          minItems: '1'
          type: number
        protocol:
          description: Service type url
          format: url
          maxItems: '1'
          minItems: '1'
          type: string
        status:
          description: Feed status
          enum:
          - Created
          - Message sent
          - Sending message failed
          maxItems: '1'
          minItems: '1'
          type: string
      type: object
    feedId:
      description: Feed id
      format: ascii no whitespace
      type: string
    feedList:
      description: Feeds by service type url
      properties:
        '[\x00-\x7F]+':
          $ref: '#/components/schemas/feedDetails'
      type: object
      x-patternProperties:
        '[\x00-\x7F]+':
          $ref: '#/components/schemas/feedDetails'
    feedRequest:
      description: Request for feed
      properties:
        input:
          default: null
          description: Server feed request input
          format: base64-encoded byte array
          maxItems: 1
          minItems: 0
          nullable: true
          type: string
        protocol:
          description: Service type url
          format: url
          maxItems: 1
          minItems: 1
          type: string
        text:
          description: Feed request remark
          maxItems: 1
          minItems: 1
          type: string
      type: object
    feedRequestCallback:
      $ref: '#/components/schemas/dataReferenceReceivedv2Event'
    feedRequestResponse:
      description: Request for feed response
      properties:
        feedId:
          maxItems: 1
          minItems: 1
          type: string
        protocol:
          description: Service type url
          format: url
          maxItems: 1
          minItems: 1
          type: string
      type: object
    feedsAccessRequest:
      description: Access requests by feed id
      properties:
        '[\x00-\x7F]+':
          properties:
            input:
              default: null
              description: Feed access request input
              format: base64-encoded byte array
              maxItems: 1
              minItems: 0
              nullable: true
              type: string
          type: object
      type: object
      x-patternProperties:
        '[\x00-\x7F]+':
          properties:
            input:
              default: null
              description: Feed access request input
              format: base64-encoded byte array
              maxItems: 1
              minItems: 0
              nullable: true
              type: string
          type: object
    feedsAccessResponse:
      description: Feed access responses by feed
      properties:
        '[\x00-\x7F]+':
          properties:
            content-type:
              maxItems: 1
              minItems: 1
              type: string
            error:
              maxItems: 1
              minItems: 1
              nullable: true
              type: string
            output:
              format: base64-encoded byte array
              maxItems: 1
              minItems: 1
              type: string
          type: object
      type: object
      x-patternProperties:
        '[\x00-\x7F]+':
          properties:
            content-type:
              maxItems: 1
              minItems: 1
              type: string
            error:
              maxItems: 1
              minItems: 1
              nullable: true
              type: string
            output:
              format: base64-encoded byte array
              maxItems: 1
              minItems: 1
              type: string
          type: object
    protocol:
      description: Service type url
      example: https://github.com/qiyfoundation/payment-due-list/tree/master/schema/v1
      format: url
      type: string
  securitySchemes:
    appAuthentication:
      $ref: https://raw.githubusercontent.com/qiyfoundation/Qiy-Scheme/review-board/Qiy-Node/openapi.json#/components/schemas/appAuthentication
    transportAuthentication:
      $ref: https://raw.githubusercontent.com/qiyfoundation/Qiy-Scheme/review-board/Qiy-Node/openapi.json#/components/schemas/transportAuthentication
    userAuthentication:
      $ref: https://raw.githubusercontent.com/qiyfoundation/Qiy-Scheme/review-board/Qiy-Node/openapi.json#/components/schemas/userAuthentication
info:
  description: To get started with [this api](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md),
    you need a developer key. You can get it [here](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#service-desk)
  externalDocs:
    description: Find more info here
    url: https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md
  license:
    name: Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International
      Public License
    url: https://creativecommons.org/licenses/by-nc-nd/4.0/
  title: Qiy Node API - Client
  version: 1.1.0
openapi: 3.0.0
paths:
  /{ConnectionFeedsEndpointPath}:
    parameters:
    - description: Connection Feeds Endpoint path, for example 'user/mgd_dev2/connections/016706d0-b3c1-4104-b6de-aacdf33230c0/feeds'
        for the Connection Feeds Endpoint 'https://dev2-user.testonly.digital-me.nl/'.
      in: path
      name: ConnectionFeedsEndpointPath
      required: true
    post:
      description: See [Request for feed](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#request-for-feed)
      operationId: Request for feed
      requestBody:
        content:
          application/json:
            examples:
              example:
                $ref: '#/components/examples/feedRequest'
            schema:
              $ref: '#/components/schemas/feedRequest'
        description: Feed request details
      responses:
        '201':
          $ref: '#/components/responses/feedRequestResponse'
        default:
          $ref: '#/components/responses/default'
      security:
      - appAuthentication: []
      - transportAuthentication: []
      - userAuthentication: []
      tags:
      - Feeds
    servers:
    - description: Connection Feeds Endpoint
      url: '{ConnectionFeedsEndpointBaseUrl}'
      variables:
        ConnectionFeedsEndpointBaseUrl:
          default: https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#connection-feeds-endpoint
          description: See [Connection Feeds Endpoint](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#connection-feeds-endpoint)
  /{FeedRequestCallbackEndpointPath}:
    parameters:
    - description: Feed Request Callback Endpoint path, for example 'qiy/request-for-feed'
        for the Feed Request Callback Endpoint 'https://client.example.com/qiy/request-for-feed'.
      in: path
      name: FeedRequestCallbackEndpointPath
      required: true
    post:
      requestBody:
        content:
          application/json:
            examples:
              example:
                $ref: '#/components/examples/feedRequestCallback'
            schema:
              $ref: '#/components/schemas/feedRequestCallback'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/feedRequestCallback'
        default:
          $ref: '#/components/responses/default'
    servers:
    - description: Request for Feed callback endpoint
      url: '{FeedRequestCallbackEndpointBaseUrl}'
      variables:
        FeedRequestCallbackEndpointBaseUrl:
          default: https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#client-feed-request-callback-endpoint
          description: See [Client Feed Request Callback Endpoint](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#client-feed-request-callback-endpoint)
  /{FeedsEndpointPath}:
    get:
      description: See [List feeds](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#list-feeds)
      operationId: List feeds
      parameters:
      - $ref: '#/components/parameters/protocol'
      responses:
        '200':
          $ref: '#/components/responses/feedList'
        default:
          $ref: '#/components/responses/default'
      tags:
      - Feeds
    parameters:
    - $ref: '#/components/parameters/feedsEndpointPath'
    post:
      description: See [Access feeds](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#access-feeds)
      operationId: Access feeds
      requestBody:
        content:
          application/json:
            examples:
              example:
                $ref: '#/components/examples/feedsAccessRequest'
            schema:
              $ref: '#/components/schemas/feedsAccessRequest'
        description: Access feeds request details
      responses:
        '200':
          $ref: '#/components/responses/feedsAccessResponse'
        default:
          $ref: '#/components/responses/default'
      tags:
      - Feeds
    servers:
    - description: Feeds Endpoint
      url: '{FeedsEndpointBaseUrl}'
      variables:
        FeedsEndpointBaseUrl:
          default: https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#feeds-endpoint
          description: See [Feeds Endpoint](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#feeds-endpoint)
  /{FeedsEndpointPath}/{feedId}:
    parameters:
    - $ref: '#/components/parameters/feedsEndpointPath'
    post:
      description: See [Access feed](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#access-feed)
      operationId: Request for feed callback
      parameters:
      - $ref: '#/components/parameters/feedId'
      requestBody:
        content:
          text:
            examples:
              example:
                description: 'An example of base64-encoded input. NB: the enclosing
                  quotes must not be part of the body.'
                value: VGhlIGJvZHkgbWF5IGluY2x1ZGUgYSBzZXJ2aWNlIGVuZHBvaW50IGZlZWQgYWNjZXNzIHJlcXVlc3QgYm9keSBlbmNvZGVkIGFzIGEgYmFzZS02NCBlbmNvZGVkIGJ5dGUgYXJyYXku
        description: Access request input encoded as a base64-encoded byte array
      responses:
        '200':
          $ref: '#/components/responses/feedAccessResponse'
        default:
          $ref: '#/components/responses/default'
      tags:
      - Feeds
    servers:
    - description: Feeds Endpoint
      url: '{FeedsEndpointBaseUrl}'
      variables:
        FeedsEndpointBaseUrl:
          default: https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#feeds-endpoint
          description: See [Feeds Endpoint](https://github.com/qiyfoundation/Qiy-Scheme/blob/review-board/Qiy-Node/Qiy%20Node%20API.md#feeds-endpoint)
security:
- appAuthentication: []
- userAuthentication: []
